In [1]:
import pandas as pd
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.embeddings import GPT4AllEmbeddings

from sentence_transformers import SentenceTransformer, util
import torch
# from langchain_community.utils.math import cosine_similarity
from sklearn.metrics.pairwise import cosine_similarity

/home/maciej/anaconda3/envs/ml_lm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
sentences = [
    "Preheat oven to 350 degrees F. Spray an 11x7x2-inch baking dish with cooking spray. In a large bowl, combine the chicken, celery and water chestnuts. Stir in the soup and mayonnaise. Spread half the mixture into the prepared pan. Unroll the dough and separate into 9 squares. Place 3 squares in the bottom of the pan. Spread with half the sour cream. Top with half the chicken mixture and half the Parmesan cheese. Repeat the layers. Bake for 40 minutes. Let stand for 10 minutes. Cut into 6 squares. Serve warm.", 
    "Preheat the oven to 375 degrees. Put the chicken, celery, water chestnuts, soup, mayonnaise and sour cream in a large bowl and stir until well combined. Put the chicken mixture into a 9x13 baking dish that has been coated with the cooking spray. Bake for 25-30 minutes, or until celery is crisp-tender. Remove the casserole from the oven. Unroll the croissant dough into flat pieces and cover the chicken mixture with the slices of dough. Drizzle with the melted butter. Bake for 10-12 minutes or until the croissant topping is turning golden brown. Remove the casserole from the oven and sprinkle with the parmesan cheese. Bake for 1-2 more minutes. Let stand 5 minutes before serving."
    ]

# sentences = [
#     "Preheat the oven to 375 degrees. Put the chicken, celery, water chestnuts, soup, mayonnaise and sour cream in a large bowl and stir until well combined. Put the chicken mixture into a 9x13 baking dish that has been coated with the cooking spray. Bake for 25-30 minutes, or until celery is crisp-tender. Remove the casserole from the oven. Unroll the croissant dough into flat pieces and cover the chicken mixture with the slices of dough. Drizzle with the melted butter. Bake for 10-12 minutes or until the croissant topping is turning golden brown. Remove the casserole from the oven and sprinkle with the parmesan cheese. Bake for 1-2 more minutes. Let stand 5 minutes before serving.",
#     "Melt butter in a large skillet over medium heat. Stir in leeks. Cover and stir often until leeks are very soft. Cook potato in salted water until almost done. To potato and water, add broccoli stems and then florets or until tender. Drain well and transfer to food processor. Add leeks to the food processor and puree all. Return puree to skillet and add cream, dill, salt and pepper. Blend well and serve."
#     ]

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
# model2 = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
model2 = GPT4AllEmbeddings()



/home/maciej/anaconda3/envs/ml_lm/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()


bert_load_from_file: gguf version     = 2
bert_load_from_file: gguf alignment   = 32
bert_load_from_file: gguf data offset = 695552
bert_load_from_file: model name           = BERT
bert_load_from_file: model architecture   = bert
bert_load_from_file: model file type      = 1
bert_load_from_file: bert tokenizer vocab = 30522


In [3]:
df = pd.read_csv("first_gen.csv")

In [4]:

pred = df.iloc[9].values[2]
y = "Cook the pasta according to package directions. Drain and rinse in cold water. Place in a large bowl. Add remaining ingredients and toss to coat. Taste and adjust with salt and pepper. Cover and refrigerate for 2 hours or overnight."

In [5]:
pred = sentences[0]
y = sentences[1]

In [6]:
pred, y

('Preheat oven to 350 degrees F. Spray an 11x7x2-inch baking dish with cooking spray. In a large bowl, combine the chicken, celery and water chestnuts. Stir in the soup and mayonnaise. Spread half the mixture into the prepared pan. Unroll the dough and separate into 9 squares. Place 3 squares in the bottom of the pan. Spread with half the sour cream. Top with half the chicken mixture and half the Parmesan cheese. Repeat the layers. Bake for 40 minutes. Let stand for 10 minutes. Cut into 6 squares. Serve warm.',
 'Preheat the oven to 375 degrees. Put the chicken, celery, water chestnuts, soup, mayonnaise and sour cream in a large bowl and stir until well combined. Put the chicken mixture into a 9x13 baking dish that has been coated with the cooking spray. Bake for 25-30 minutes, or until celery is crisp-tender. Remove the casserole from the oven. Unroll the croissant dough into flat pieces and cover the chicken mixture with the slices of dough. Drizzle with the melted butter. Bake for 1

In [7]:
embedding_1 = model.encode(y, convert_to_tensor=True).cpu()
embedding_2 = model.encode(pred, convert_to_tensor=True).cpu()

util.pytorch_cos_sim(embedding_1, embedding_2)

tensor([[0.8683]])

In [9]:
cosine_similarity([embedding_1], [embedding_2])

array([[0.868348]], dtype=float32)

In [ ]:
# 23.5
#Compute embedding for both lists
embedding_1 = torch.Tensor(model2.embed_query(y)).cpu()
embedding_2 = torch.Tensor(model2.embed_query(pred)).cpu()

util.pytorch_cos_sim(embedding_1, embedding_2)

tensor([[0.8704]])

In [10]:
cosine_similarity([embedding_1], [embedding_2])

array([[0.868348]], dtype=float32)